blogbase/blogbase/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views
from filebrowser.sites import site
from django.contrib import admin

#name space defines the name used in your links when calling
#and looping through posts and categories, as dsblog, if you change this
#you also need to change the links where it calls a hef ref... 'dsblog:post_list

#also need to ensure that the include urls matches the app urls location
#and again ensure that after r'', there is nothing so not to keep looking
#and accepting any url path that is entered

urlpatterns = [
    url(r'^where_the_magic_happens/', include(admin.site.urls)),
    url(r'^admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    url(r'', include('dsblog.urls', app_name='dsblog', namespace='dsblog')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^where_the_magic_happens/filebrowser/', include(site.urls)),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blogbase/dsblog/urls.py
from .views import *
from django.conf.urls import *
from django.conf import settings
from django.views.generic.base import TemplateView
from .views import sendmail

#shows the feedback form page in conjunction with the url and view.
#works with the url in feedback form
app_name='form'

urlpatterns = [
    url(r'^$', post_list, name="post_list"),
    url(r'^post/(?P<slug>[-\w]+)/$', post_detail, name="post_detail"),
    url(r'^category/(?P<slug>[-\w]+)/$', category_detail, name="category_detail"),
    url(r'^email/send/$', sendmail),
    url(r'^email/thankyou/$', TemplateView.as_view(template_name="thankyou.html"), name="thankyou"),
    url(r'^email/$', TemplateView.as_view(template_name="email.html"), name="email"),
    url(r'^images/$', images, name="images"),
    url(r'^astro/$', astro, name="astro"),
    url(r'^crypto/$', crypto, name="crypto"),
    url(r'^about/$', about, name="about"),
    url(r'^privacypolicy/$', privacy_policy, name="privacy_policy"),
    url(r'^commentpolicy/$', comment_policy, name="comment_policy"),
    url(r'^results/$', search, name="search"),
    url(r'^matt-cheetham-cv-2018/$', cv, name="cv"),
]

#the name for post detail and category detail matches the a href links
#in the templates. Also the slug is passed as an argument into the Links

#also need to make sure the post list just has ^$ otherwise you can keep
#typing any urlpath into the browser bar and it'll match it
#it says to django to stop looking at the raw string

blogbase/dsblog/models.py
from django.db import models
from django import forms
from django.utils import timezone
from tinymce import HTMLField
from django.template.defaultfilters import slugify

#model for category creation in the database
class Category(models.Model):
    title = models.CharField(max_length=250)
    description = models.CharField(max_length=250)
    slug = models.SlugField(max_length=200, unique=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    # save function returns slug with title
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Category, self).save(*args, **kwargs)
    #returns the title as a string value
    def __str__(self):
        return self.title
    #non-field type - sets plural name for category
    class Meta:
        verbose_name_plural = "Categories"

#model for post creation in the database
class Post(models.Model):
    #choices in tuple form iteratable and shows select box instead
    STATUS_CHOICES = (
        ('Published', 'Published'),
        ('Draft', 'Draft'),
    )
    author = models.ForeignKey('auth.User')
    title = models.CharField(max_length=200)
    text = HTMLField('Content')
    tagline = models.TextField()
    image = models.ImageField()
    category = models.ForeignKey(Category)
    slug = models.SlugField(max_length=200, unique=True)
    status = models.CharField(max_length=10, default='Draft', choices=STATUS_CHOICES)
    created_date = models.DateTimeField(auto_now_add=True)
    published_date = models.DateTimeField(default=timezone.now)
    #args/kwargs unpacks all potential arguments
    #ensure super class touches the database and saves the object
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)
    #displays title as string
    def __str__(self):
        return self.title

#model for email form creation in the database
class EmailForm(forms.Form):
      firstname = forms.CharField(max_length=255)
      lastname = forms.CharField(max_length=255)
      email = forms.EmailField()
      subject = forms.CharField(max_length=255)
      botcheck = forms.CharField(max_length=5)
      message = forms.CharField()

#model for form feedback creation in the database
class Feedback(models.Model):

    company = models.CharField(max_length=50)
    position_feedback = models.TextField(max_length=255)
    cv_feedback = models.TextField(max_length=255)
    date = models.DateTimeField(auto_now_add=True)
    #displays company as string
    def __str__(self):
        return self.company
    #sets admin page plural name
    class Meta:
        verbose_name_plural = "Feedback"

blogbase/dsblog/forms.py
from django import forms
from .models import *
from django.db import models

#works with the email model to setup email forms, and use the variables
class ContactForm(forms.Form):
    contact_name = forms.CharField(required=True)
    contact_email = forms.EmailField(required=True)
    content = forms.CharField(required=True, widget=forms.Textarea)

#meta takes the feedback model so there's no need to duplicate variables
#model assigns to which model and fields defines which fields will be shown in the templates
#exclude does the opposite
class FeedbackForm(forms.ModelForm):

    class Meta:
        model = Feedback
        fields = ['company', 'position_feedback', 'cv_feedback']
        exclude = ['date']

blogbase/dsblog/views.py
from django.shortcuts import render, get_object_or_404
from .models import *
from django.utils import timezone
from django.shortcuts import redirect
from .forms import *
from django.core.mail import EmailMessage
from django.template.loader import get_template
from django.template import Context
from django.views.generic.base import TemplateView
from django.http import HttpResponseRedirect
from django.core.mail import send_mail, BadHeaderError
from django.db.models import Q
from blogbase.config import *

#defines the post list view that returns the post_list.html as filtered by published
#the objects_list variable is what gets called in the post detail and category a href links in the templates
#if the variable changes please update links

#pagination also is now seperated into it's own file within blogbase.config
#num=5 shows 5 posts per page, pages under context is set at 1 amending this creates an error
#also need to have the more posts than the num=5 minimum otherwise it won't display the links
def post_list(request):
    template = 'blog/post_list.html'
    objects_list = Post.objects.filter(status='Published',
        published_date__lte=timezone.now()).order_by('-published_date')

    pages = pagination(request, objects_list, num=5)

    context = {
        'items': pages[0],
        'page_range': pages[1],
    }
    return render(request, template, context)


#defines the post detail view
def post_detail(request, slug):
    template = 'blog/post_detail.html'

    post = get_object_or_404(Post, slug=slug)
    context = {
        'post': post,
    }
    return render(request, template, context)


#defines the category detail view, now passes in 2 parameters incl slug
#which need to be configured under views and urls
def category_detail(request, slug):
    template = 'blog/category_detail.html'
    #category argument only shows category
    category = get_object_or_404(Category, slug=slug)
    post = Post.objects.filter(category=category)

    context = {
    'category': category,
    'post': post,
    }
    return render(request, template, context)


#defines search function with the q method icontains creates the search
def search(request):
    template = 'blog/post_list.html'

    query = request.GET.get('q')

    if query:
        results = Post.objects.filter(Q(title__icontains=query) | Q(text__icontains=query))
    else:
        results = Post.objects.filter(status="Published")

    pages = pagination(request, results, num=5)

    context = {
        'items': pages[0],
        'page_range': pages[1],
        'query': query,
    }
    return render(request, template, context)


#defines the send email logic and works with the .forms 
def sendmail(request):
      if request.method == 'POST':
        form = EmailForm(request.POST)
        if form.is_valid():
          firstname = form.cleaned_data['firstname']
          lastname = form.cleaned_data['lastname']
          email = form.cleaned_data['email']
          subject = form.cleaned_data['subject']
          botcheck = form.cleaned_data['botcheck'].lower()
          message = form.cleaned_data['message']
          if botcheck == 'yes':
            try:
              fullemail = firstname + " " + lastname + " " + "<" + email + ">"
              send_mail(subject, message, fullemail, ['matt.cheetham@darkskiesblog.co.uk'])
              return HttpResponseRedirect('/email/thankyou/')
            except:
              return HttpResponseRedirect('/email/')
        else:
          return HttpResponseRedirect('/email/')
      else:
        return HttpResponseRedirect('/email/')


#defines links to pages, returns and renders pages
def images(request):
    return render(request, 'blog/images.html', {})

def astro(request):
    return render(request, 'blog/astro.html', {})

def crypto(request):
    return render(request, 'blog/crypto.html', {})

def about(request):
    return render(request, 'blog/about.html', {})

def privacy_policy(request):
    return render(request, 'blog/privacy_policy.html', {})

def comment_policy(request):
    return render(request, 'blog/comment_policy.html', {})

#defines the cv view including the feedback form
def cv(request):

    if request.method == "POST":
        form = FeedbackForm(request.POST)

        if form.is_valid():
            company = form.cleaned_data['company']
            position_feedback = form.cleaned_data['position_feedback']
            cv_feedback = form.cleaned_data['cv_feedback']
            form.save()
            return render(request, 'blog/cv.html')

    else:
        form = FeedbackForm()

    return render(request, 'blog/cv.html', {'form': form})

blogbase/dsblog/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}


<html>
    <head>
	     <title>Dark Skies | Astrophotography & Tech Blog</title>
       <!-- css stylesheet and js links -->
       <meta name="viewport" content="width=device-width, initial-scale=1">
       <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
       <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css">
       <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
       <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
       <link rel="stylesheet" href="{% static 'css/blog.css' %}">
       <script src="{% static 'js/w3css.js' %}"></script>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <!-- allows tinymce langauge display and highlight-->
        <link href="{% static "styles/atom-one-dark.css" %}" rel="stylesheet">
        <script src="{% static "highlight.pack.js" %}"></script>
        <script>hljs.initHighlightingOnLoad();</script>
        <!-- cookie banner to display on pages-->
        <script type="text/javascript" id="cookiebanner" src="http://cookiebanner.eu/js/cookiebanner.min.js"></script>
        <script>$(document).ready(function() {
            $('body').append($('footer'));
        });
        </script>

        <!-- google adsense api script -->
        <script>
          (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
          })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
          ga('create', 'UA-99579367-1', 'auto');
          ga('send', 'pageview');
        </script>
            <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
            <script>
            (adsbygoogle = window.adsbygoogle || []).push({
            google_ad_client: "ca-pub-7287882220684154",
            enable_page_level_ads: true
            });
            </script>
    </head>

<body>

<div class="content">

    <div class="header">
      DARK SKIES
      <h4>Astrophotography & Tech Blog</h4>
      <div class="w3-xlarge">
          <a href="https://www.instagram.com/dark_skies_blog" target="_blank"><i class="fab fa-instagram w3-hover-opacity"></i></a>
          <a href="https://twitter.com/DarkSkiesBlog" target="_blank"><i class="fab fa-twitter-square w3-hover-opacity"></i></a>
      </div>
    </div>

    <!-- Navbar for large and desktop screens -->
    <div class="navbar">
  	   <a href="/" class="w3-bar-item w3-button w3-mobile">HOME</a>
       <a href="/astro" class="w3-bar-item w3-button w3-mobile">ASTRONOMY</a>
  	   <a href="/images" class="w3-bar-item w3-button w3-mobile">IMAGES</a>
  	   <a href="/crypto" class="w3-bar-item w3-button w3-mobile">CRYPTOCOIN</a>
  	   <a href="/about" class="w3-bar-item w3-button w3-mobile">ABOUT</a>
  	   <a href="/email" class="w3-bar-item w3-button w3-mobile">CONTACT</a>

          <!--form method for the search functionality-->
          <form method="GET" action="{% url 'dsblog:search' %}">
            <input class="w3-input-x w3-border w3-mobile" style="width:20%" name="q" value="{{ request.GET.q }}" placeholder="Search..">
            <button type="submit" class="w3-button w3-black w3-mobile">GO</button>
          </form>
      </div>

    <!-- creates the left side column -->
    <div class="row">
      <div class="leftcolumn">
        {% block content %}
        {% endblock %}
      </div>

    <!-- creates the right floating column -->
    <div class="rightcolumn">
      <div class="card">
        <h2>About DS</h2>
          <p>This site is dedicated to all things Astrophotography, Technology, Sci-Fi, Popular Science, and Cryptocoins.
            Our goal is for this site to be a platform for people to be able to discover and get involved with new projects.<p>
            I hope you enjoy the website, check out the about section to get in touch <a class="w3-ul" href="/about">here</a><p></p>
      </div>

      <div class="card">
        <h3>Quick Links</h3>
        <button onclick="myFunction('1')" class="w3-button w3-block w3-black w3-center-align">
        Astrophotography</button>

        <div id="1" class="w3-hide">
          <a class="w3-button w3-block w3-left-align" href="http://www.astropix.com/HTML/I_ASTROP/INTRO.HTM" target="_blank">Astropix Tutorial</a>
          <a class="w3-button w3-block w3-left-align" href="http://iso.500px.com/basic-astrophotography-tutorial/" target="_blank">ISO500 Tutorial</a>
          <a class="w3-button w3-block w3-left-align" href="http://www.astrobackyard.com/learn-astrophotography/" target="_blank">Astro Backyard Tutorial</a>
          <a class="w3-button w3-block w3-left-align" href="http://cosmicpursuits.com/articles/" target="_blank">Cosmic Pursuits</a>
          <a class="w3-button w3-block w3-left-align" href="http://www.moonphases.co.uk/" target="_blank">Moonphases</a>
          <a class="w3-button w3-block w3-left-align" href="http://www.lightpollutionmap.info/#zoom=13&lat=6738673&lon=-250684&layers=0BTFFFFF" target="_blank">Light Pollution Map</a>
        </div>

        <button onclick="myFunction('2')" class="w3-button w3-block w3-black w3-center-align">
        Technology</button>

        <div id="2" class="w3-hide">
          <a class="w3-button w3-block w3-left-align" href="http://www.engadget.com/uk/" target="_blank">Engadget UK</a>
          <a class="w3-button w3-block w3-left-align" href="http://www.wired.co.uk/" target="_blank">Wired</a>
          <a class="w3-button w3-block w3-left-align" href="http://www.gizmodo.co.uk/" target="_blank">Gizmodo</a>
          <a class="w3-button w3-block w3-left-align" href="http://getpocket.com" target="_blank">Pocket</a>
          <a class="w3-button w3-block w3-left-align" href="http://www.popularmechanics.com/technology/" target="_blank">Popular Mechanics</a>
        </div>

        <button onclick="myFunction('3')" class="w3-button w3-block w3-black w3-center-align">
        Popular Science</button>

        <div id="3" class="w3-hide">
          <a class="w3-button w3-block w3-left-align" href="http://www.popsci.com" target="_blank">Popular Science</a>
          <a class="w3-button w3-block w3-left-align" href="http://www.phys.org" target="_blank">Physics.org</a>
          <a class="w3-button w3-block w3-left-align" href="http://www.home.cern/" target="_blank">Cern</a>
          <a class="w3-button w3-block w3-left-align" href="https://www.livescience.com/" target="_blank">Live Science</a>
        </div>

        <button onclick="myFunction('4')" class="w3-button w3-block w3-black w3-center-align">
        Sci-Fi</button>

        <div id="4" class="w3-hide">
          <a class="w3-button w3-block w3-left-align" href="http://sciencefiction.com/" target="_blank">Science Fiction</a>
          <a class="w3-button w3-block w3-left-align" href="http://www.denofgeek.com/uk" target="_blank">Den Of Geek</a>
          <a class="w3-button w3-block w3-left-align" href="http://www.scifinow.co.uk" target="_blank">SciFi Now</a>
        </div>

        <button onclick="myFunction('5')" class="w3-button w3-block w3-black w3-center-align">
        Podcasts</button>

        <div id="5" class="w3-hide">
          <a class="w3-button w3-block w3-left-align" href="http://www.adam-buxton.co.uk/" target="_blank">Adam Buxton Podcast</a>
          <a class="w3-button w3-block w3-left-align" href="http://www.bbc.co.uk/programmes/b00snr0w/episodes/downloads" target="_blank">The Infinite Monkey Cage</a>
          <a class="w3-button w3-block w3-left-align" href="http://www.stuffyoushouldknow.com/podcasts" target="_blank">Stuff You Should Know</a>
          <a class="w3-button w3-block w3-left-align" href="http://www.startalkradio.net/" target="_blank">Startalk</a>
          <a class="w3-button w3-block w3-left-align" href="http://www.bbc.co.uk/programmes/b015sqc7/episodes/downloads" target="_blank">A Life Scientific</a>
        </div>
        </div>

        <!-- creates the footer style -->
        <div class="card">
          <h3>Twitter Feed</h3>
              <blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">The LHC has found the Higgs works perfectly – which is a problem <a href="https://t.co/9p4y3hke08">https://t.co/9p4y3hke08</a> <a href="https://t.co/IYSy59MTZY">pic.twitter.com/IYSy59MTZY</a></p>&mdash; New Scientist (@newscientist) <a href="https://twitter.com/newscientist/status/1005549527330443264?ref_src=twsrc%5Etfw">June 9, 2018</a></blockquote>
              <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
        </div>

        <!-- support sectionunder right had side column -->
      <div class="card">
        <h3>Support</h3>
            <p>If you would like to help support the Dark Skies development you can do so via PayPal below...<p>
              <form action="https://www.paypal.com/cgi-bin/webscr" target="_blank" method="post" target="_top">
                <input type="hidden" name="cmd" value="_s-xclick">
                <input type="hidden" name="hosted_button_id" value="TSWD6JLH86KVN">
                <input type="image" src="https://www.paypalobjects.com/webstatic/en_US/i/btn/png/blue-rect-paypal-26px.png" border="0" name="submit" alt="PayPal – The safer, easier way to pay online!">
                <img alt="" border="0" src="https://www.paypalobjects.com/en_GB/i/scr/pixel.gif" width="1" height="1">
              </form><p></p>
              <div class="wordwrap">
                  <p>Bitcoin wallet here<p>
                    <input type="text" value="358vi1Zwic7Q4oWQxwDkh57eGjQAVv9zSp" id="myInput">
                  <button class="w3-btn w3-grey" onclick="Copy()">Copy</button>
                  <p>Golem wallet here<p>
                    <input type="text" value="0x93b8a681e8142f9a809da85cb74f09b86271c70c" id="myInput">
                  <button class="w3-btn w3-grey" onclick="Copy()">Copy</button>
              </div>
      </div>
    </div>
  </div>
<!-- creates the footer style -->
  <div class="footer">
    <a class="w3-ul" href="//www.dmca.com/Protection/Status.aspx?ID=93cf6bf8-eea2-40e2-9a13-50f881d2e373" title="DMCA.com Protection Status" class="dmca-badge"> <img src="//images.dmca.com/Badges/dmca_protected_sml_120ak.png?ID=93cf6bf8-eea2-40e2-9a13-50f881d2e373" alt="DMCA.com Protection Status"></a> <script src="//images.dmca.com/Badges/DMCABadgeHelper.min.js"> </script>
    Copyright &copy 2018 Dark Skies. All rights reserved. Hand built with <a class="w3-ul" href="https://www.djangoproject.com" target="_blank">Django</a> and <a class="w3-ul" href="https://www.python.org" target="_blank">Python.
    <p><a class="w3-ul" href="/privacypolicy" target="_blank">Privacy Policy</a>   |   <a class="w3-ul" href="/commentpolicy" target="_blank">Comment Policy</a></p>
  </div>

</div>
    <!-- disqus comments section -->
    <script id="dsq-count-scr" src="//thedsblog.disqus.com/count.js" async></script>
</body>
</html>

blogbase/dsblog/templates/email.html
<!--post.text|safe enables html output and displays Images-->

{% extends 'base.html' %}

{% block content %}
    <div class="card">
              <div class="w3-container w3-grey">
                <h3>Send A Message</h3>
              </div>

      <form class="w3-container" method="post" action="/email/send/">{% csrf_token %}
        <p>
          <label class="w3-text-black"><b>First Name</b></label>
          <input name="firstname" maxlength="100" class="w3-input w3-border w3-grey" class="required" type="text"></p>
        <p>
          <label class="w3-text-black"><b>Last Name</b></label>
          <input name="lastname" maxlength="100"class="w3-input w3-border w3-grey" class="required" type="text"></p>
        <p>
	        <label class="w3-text-black"><b>Email Address</b></label>
          <input name="email" maxlength="100" class="w3-input w3-border w3-grey" class="required" type="text"></p>
  	    <p>
	        <label class="w3-text-black"><b>Subject</b></label>
          <input name="subject" maxlength="100" class="w3-input w3-border w3-grey" class="required" type="text"></p>
        <p>
	        <label class="w3-text-black"><b>Message</b></label>
          <textarea name="message" class="w3-input w3-border w3-grey" maxlength="255" class="required" type="text"></textarea></p>
        <p>
	        <label class="w3-text-black"><b>Enter "yes" to confirm</b></label>
          <input name="botcheck" maxlength="5" size="5" class="w3-input w3-border w3-grey" type="text"></p>

           <button type="submit" name="submitform" class="w3-btn w3-grey" style="font-weight: bold">Send</button></p>
      </form>
  </div>

{% endblock content %}

blogbase/dsblog/templates/pagination.html
<!--{% if query %}&q={{ query }}{% endif %} this ensures that the search stays even if you move pages-->
<!--so if a user enters something in search and moves to another page on the pagination links-->
<!--it ensures the search stays in the box-->

<div class="w3-bar">
{% if items.has_other_pages %}

      {% if items.has_previous %}

            <a href="?page={{ items.previous_page_number }}{% if query %}&q={{ query }}{% endif %}" class="w3-button">&laquo;</a>
      {% else %}
            <a class="w3-button">&laquo;</a>
      {% endif %}

      {% for i in page_range %}
      {% if items.number == i %}
                <a href="#" class="w3-button">{{ i }}</a>
      {% else %}
                <a href="?page={{ i }}{% if query %}&q={{ query }}{% endif %}" class="w3-button">{{ i }}</a>
      {% endif %}
      {% endfor %}

      {% if items.has_next %}
                <a href="?page={{ items.next_page_number }}{% if query %}&q={{ query }}{% endif %}" class="w3-button">&raquo;</a>
      {% else %}
                <a class="w3-button">&raquo;</a>
      {% endif %}

{% endif %}
</div>

blogbase/dsblog/templates/thankyou.html
<!--post.text|safe enables html output and displays Images-->

{% extends 'base.html' %}

{% block content %}
  <div class="card">
    <div class="w3-container w3-grey">
      <h3>Contact Us - Thank You</h3>
    </div>
      <p>Your email was sent and I will get back to you as soon as I can.</p>
      <p>Return to home page... <a class="w3-ul" href="/">CLICK HERE</a></p>
  </div>
{% endblock content %}