blogbase/blogbase/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views
from filebrowser.sites import site
from django.contrib import admin

#name space defines the name used in your links when calling
#and looping through posts and categories, as dsblog, if you change this
#you also need to change the links where it calls a hef ref... 'dsblog:post_list

#also need to ensure that the include urls matches the app urls location
#and again ensure that after r'', there is nothing so not to keep looking
#and accepting any url path that is entered

urlpatterns = [
    url(r'^where_the_magic_happens/', include(admin.site.urls)),
    url(r'^admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    url(r'', include('dsblog.urls', app_name='dsblog', namespace='dsblog')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^where_the_magic_happens/filebrowser/', include(site.urls)),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blogbase/dsblog/urls.py
from .views import *
from django.conf.urls import *
from django.conf import settings
from django.views.generic.base import TemplateView
from .views import sendmail

#shows the feedback form page in conjunction with the url and view.
#works with the url in feedback form
app_name='form'

urlpatterns = [
    url(r'^$', post_list, name="post_list"),
    url(r'^post/(?P<slug>[-\w]+)/$', post_detail, name="post_detail"),
    url(r'^category/(?P<slug>[-\w]+)/$', category_detail, name="category_detail"),
    url(r'^email/send/$', sendmail),
    url(r'^email/thankyou/$', TemplateView.as_view(template_name="thankyou.html"), name="thankyou"),
    url(r'^email/$', TemplateView.as_view(template_name="email.html"), name="email"),
    url(r'^images/$', images, name="images"),
    url(r'^astro/$', astro, name="astro"),
    url(r'^crypto/$', crypto, name="crypto"),
    url(r'^about/$', about, name="about"),
    url(r'^privacypolicy/$', privacy_policy, name="privacy_policy"),
    url(r'^commentpolicy/$', comment_policy, name="comment_policy"),
    url(r'^results/$', search, name="search"),
    url(r'^matt-cheetham-cv-2018/$', cv, name="cv"),
]

#the name for post detail and category detail matches the a href links
#in the templates. Also the slug is passed as an argument into the Links

#also need to make sure the post list just has ^$ otherwise you can keep
#typing any urlpath into the browser bar and it'll match it
#it says to django to stop looking at the raw string

blogbase/dsblog/models.py
from django.db import models
from django import forms
from django.utils import timezone
from tinymce import HTMLField
from django.template.defaultfilters import slugify

#model for category creation in the database
class Category(models.Model):
    title = models.CharField(max_length=250)
    description = models.CharField(max_length=250)
    slug = models.SlugField(max_length=200, unique=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    # save function returns slug with title
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Category, self).save(*args, **kwargs)
    #returns the title as a string value
    def __str__(self):
        return self.title
    #non-field type - sets plural name for category
    class Meta:
        verbose_name_plural = "Categories"

#model for post creation in the database
class Post(models.Model):
    #choices in tuple form iteratable and shows select box instead
    STATUS_CHOICES = (
        ('Published', 'Published'),
        ('Draft', 'Draft'),
    )
    author = models.ForeignKey('auth.User')
    title = models.CharField(max_length=200)
    text = HTMLField('Content')
    tagline = models.TextField()
    image = models.ImageField()
    category = models.ForeignKey(Category)
    slug = models.SlugField(max_length=200, unique=True)
    status = models.CharField(max_length=10, default='Draft', choices=STATUS_CHOICES)
    created_date = models.DateTimeField(auto_now_add=True)
    published_date = models.DateTimeField(default=timezone.now)
    #args/kwargs unpacks all potential arguments
    #ensure super class touches the database and saves the object
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)
    #displays title as string
    def __str__(self):
        return self.title

#model for email form creation in the database
class EmailForm(forms.Form):
      firstname = forms.CharField(max_length=255)
      lastname = forms.CharField(max_length=255)
      email = forms.EmailField()
      subject = forms.CharField(max_length=255)
      botcheck = forms.CharField(max_length=5)
      message = forms.CharField()

#model for form feedback creation in the database
class Feedback(models.Model):

    company = models.CharField(max_length=50)
    position_feedback = models.TextField(max_length=255)
    cv_feedback = models.TextField(max_length=255)
    date = models.DateTimeField(auto_now_add=True)
    #displays company as string
    def __str__(self):
        return self.company
    #sets admin page plural name
    class Meta:
        verbose_name_plural = "Feedback"

blogbase/dsblog/forms.py
from django import forms
from .models import *
from django.db import models

#works with the email model to setup email forms, and use the variables
class ContactForm(forms.Form):
    contact_name = forms.CharField(required=True)
    contact_email = forms.EmailField(required=True)
    content = forms.CharField(required=True, widget=forms.Textarea)

#meta takes the feedback model so there's no need to duplicate variables
#model assigns to which model and fields defines which fields will be shown in the templates
#exclude does the opposite
class FeedbackForm(forms.ModelForm):

    class Meta:
        model = Feedback
        fields = ['company', 'position_feedback', 'cv_feedback']
        exclude = ['date']

blogbase/dsblog/views.py
from django.shortcuts import render, get_object_or_404
from .models import *
from django.utils import timezone
from django.shortcuts import redirect
from .forms import *
from django.core.mail import EmailMessage
from django.template.loader import get_template
from django.template import Context
from django.views.generic.base import TemplateView
from django.http import HttpResponseRedirect
from django.core.mail import send_mail, BadHeaderError
from django.db.models import Q
from blogbase.config import *

#defines the post list view that returns the post_list.html as filtered by published
#the objects_list variable is what gets called in the post detail and category a href links in the templates
#if the variable changes please update links

#pagination also is now seperated into it's own file within blogbase.config
#num=5 shows 5 posts per page, pages under context is set at 1 amending this creates an error
#also need to have the more posts than the num=5 minimum otherwise it won't display the links
def post_list(request):
    template = 'blog/post_list.html'
    objects_list = Post.objects.filter(status='Published',
        published_date__lte=timezone.now()).order_by('-published_date')

    pages = pagination(request, objects_list, num=5)

    context = {
        'items': pages[0],
        'page_range': pages[1],
    }
    return render(request, template, context)


#defines the post detail view
def post_detail(request, slug):
    template = 'blog/post_detail.html'

    post = get_object_or_404(Post, slug=slug)
    context = {
        'post': post,
    }
    return render(request, template, context)


#defines the category detail view, now passes in 2 parameters incl slug
#which need to be configured under views and urls
def category_detail(request, slug):
    template = 'blog/category_detail.html'
    #category argument only shows category
    category = get_object_or_404(Category, slug=slug)
    post = Post.objects.filter(category=category)

    context = {
    'category': category,
    'post': post,
    }
    return render(request, template, context)


#defines search function with the q method icontains creates the search
def search(request):
    template = 'blog/post_list.html'

    query = request.GET.get('q')

    if query:
        results = Post.objects.filter(Q(title__icontains=query) | Q(text__icontains=query))
    else:
        results = Post.objects.filter(status="Published")

    pages = pagination(request, results, num=5)

    context = {
        'items': pages[0],
        'page_range': pages[1],
        'query': query,
    }
    return render(request, template, context)


#defines the send email logic and works with the .forms 
def sendmail(request):
      if request.method == 'POST':
        form = EmailForm(request.POST)
        if form.is_valid():
          firstname = form.cleaned_data['firstname']
          lastname = form.cleaned_data['lastname']
          email = form.cleaned_data['email']
          subject = form.cleaned_data['subject']
          botcheck = form.cleaned_data['botcheck'].lower()
          message = form.cleaned_data['message']
          if botcheck == 'yes':
            try:
              fullemail = firstname + " " + lastname + " " + "<" + email + ">"
              send_mail(subject, message, fullemail, ['matt.cheetham@darkskiesblog.co.uk'])
              return HttpResponseRedirect('/email/thankyou/')
            except:
              return HttpResponseRedirect('/email/')
        else:
          return HttpResponseRedirect('/email/')
      else:
        return HttpResponseRedirect('/email/')


#defines links to pages, returns and renders pages
def images(request):
    return render(request, 'blog/images.html', {})

def astro(request):
    return render(request, 'blog/astro.html', {})

def crypto(request):
    return render(request, 'blog/crypto.html', {})

def about(request):
    return render(request, 'blog/about.html', {})

def privacy_policy(request):
    return render(request, 'blog/privacy_policy.html', {})

def comment_policy(request):
    return render(request, 'blog/comment_policy.html', {})

#defines the cv view including the feedback form
def cv(request):

    if request.method == "POST":
        form = FeedbackForm(request.POST)

        if form.is_valid():
            company = form.cleaned_data['company']
            position_feedback = form.cleaned_data['position_feedback']
            cv_feedback = form.cleaned_data['cv_feedback']
            form.save()
            return render(request, 'blog/cv.html')

    else:
        form = FeedbackForm()

    return render(request, 'blog/cv.html', {'form': form})

blogbase/dsblog/templates/blog/about.html
<!--post.text|safe enables html output and displays Images-->

{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
  <div class="card">
      <div class="w3-container w3-grey">
        <h3>The Mission</h3>
      </div>
      <p>
    If you've ever thought about getting into Astrophotography, just love looking at the images, or you want to understand more about Astronomy, Sci-Fi, Technology or just want something different to read, then this one is for you.<P>
  </div>

  <div class="card">
      <div class="w3-container w3-grey">
        <h3>About Me</h3>
      </div>
      <p>
    <img class="w3-round" src="{% static 'images/me.jpg' %}" height="150" width=120 style="float: left; margin-right: 15px"/></a>
        I'm an amateur Astrophotographer from Bristol who loves Snowboarding, Skating, Coding, Podcasts, Sci-Fi and Popular Science.
          I would like to end by thanking my girlfriend, friends and family for all of their help and support.<p>
              <p>
        <div class="w3-xxxlarge">
          <a href="https://www.facebook.com/mcheetham" target="_blank"><i class="fab fa-facebook w3-hover-opacity"></i></a>
          <a href="https://www.instagram.com/mgcheetham" target="_blank"><i class="fab fa-instagram w3-hover-opacity"></i></a>
          <a href="https://www.linkedin.com/in/mgcheetham" target="_blank"><i class="fab fa-linkedin w3-hover-opacity"></i></a>
          <br/>
          <br/>
        </div>
 </div>
<p>

  <div class="card">
      <div class="w3-container w3-grey">
        <h3>Updates</h3>
      </div>
      <p>
        <div class="w3-container">
        <div class="w3-responsive">
        <table class="w3-table-all">
        <tr>
          <th>Date</th>
          <th>Update</th>
        </tr>

        <tr>
          <td>10.06.2018</td>
          <td>I've finally gotten around to revamping the website and making it more responsive to mobile and tablet devices. I've also added in some extra pages and changed the color scheme.</td>
        </tr>

        <tr>
          <td>09.01.2018</td>
          <td>After an extended absense I've gotten around to updating the blog post list and adding in some extra visual aides.</td>
        </tr>

        <tr>
          <td>19.10.2017</td>
          <td>I've updated the blog list view to include images, added in a tagline and made some other minor alterations. I've also migrated the version control over to bitbucket.</td>
        </tr>

        <tr>
          <td>07.03.2017</td>
          <td>This site is my first major project as a developer and i'll continue to maintain and develop it further as I'm learning new skills. The next challenge is to make the site more user and mobile friendly with javascript, bootstrap and CSS.<p>
            If you would like to contribute in any way then please get in touch on either on instagram / twitter or send me an email through on the contact page <a class="w3-ul" href="/email" target="_blank">here</a></td>
        </tr>

        </table>
        </div>
        </div>
  </div>
<p>
{% endblock content %}

blogbase/dsblog/templates/blog/astro.html
<!--post.text|safe enables html output and displays Images-->

{% extends 'base.html' %}

{% block content %}
<div class="card">
  <div class="w3-container w3-grey">
      <h3>Astro Weather</h3>
    </div>
    <p>
      <iframe src="https://www.meteoblue.com/en/weather/widget/seeing?geoloc=detect&noground=0"  frameborder="0" scrolling="NO" allowtransparency="true" sandbox="allow-same-origin allow-scripts allow-popups allow-popups-to-escape-sandbox" style="width: 520px;height: 754px"></iframe><div><!-- DO NOT REMOVE THIS LINK --><a href="https://www.meteoblue.com/en/weather/forecast/seeing?utm_source=weather_widget&utm_medium=linkus&utm_content=seeing&utm_campaign=Weather%2BWidget" target="_blank">meteoblue</a></div>
    </p>
</div>

<div class="card">
  <div class="w3-container w3-grey">
    <h3>ISS Information</h3>
  </div>
</div>
{% endblock content %}

blogbase/dsblog/templates/blog/category_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="card">
    <div class="w3-container w3-grey">
      <h3>{{ category.title }} Category</h3>
    </div>
      <p>
        <h4>Description:</h4><h6>{{ category.description }}</h6>
      <p>
        <a class="w3-ul" href="/">HOME</a>

      </div>

      <div class="card">
          <h4>Posts</h4>
          <p>
            {% for item in post %}
              <a class="w3-ul" href="{% url 'dsblog:post_detail' slug=item.slug %}">{{ item.title }}</a>
              <p>
              Published on {{ item.published_date }}</a>
            <p>
        {% endfor %}
      </div>
{% endblock %}

blogbase/dsblog/templates/blog/comment_policy.html
<!--post.text|safe enables html output and displays Images-->
<!DOCTYPE html>
{% load staticfiles %}

<html>
    <head>
       <!-- css stylesheet and js links -->
       <meta name="viewport" content="width=device-width, initial-scale=1">
       <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
       <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css">
       <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
       <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
       <link rel="stylesheet" href="{% static 'css/blog.css' %}">
       <script src="{% static 'js/w3css.js' %}"></script>
     </head>
  <body>

  <div class="card">
    <div class="w3-container w3-grey">
      <bold><h1>Dark Skies Blog</h1></bold>
    </div>
    <p>
      We want you to feel at home when you post a comment on our site.<p>
      We reserve the right to delete comments and ban users as needed to keep the comment threads here civil and substantive.
      <p>
      <h2>Our No. 1 rule</h2><h4>Please don’t be a jerk.</h4>
      <p>
      <h2>Here’s what we like to see in comments:</h2>
      <p>
      <h3>Weigh in</h3> with smart, informed ideas that contribute further to the story.
      <p>
      <h3>Give us</h3> useful, constructive criticism. Spot a typo or an error? Let us know and we will correct it.
      <p>
      <h3>Demonstrate</h3> and share the intelligence, wisdom, and humor we know you possess.
      <p>
      <h3>Don’t feed the trolls</h3> No not those fuzzy guys. You can however downvote and flag comments instead.
      <p>
        <br>
      <h2>And of course what we don't want to see:</h2>
      <p>
      <h3>Promoting your own brand, product, or blog</h3> We are all for collaboration and promotion as long as it stays relevant.
      <p>
      <h3>Impersonating authors or other commenters</h3> We can’t believe we have to say this, but: Don’t do that. It’s weird.
      <p>
      <h3>Comments that make it clear you didn’t read the article</h3> If skipping to the end is your style, it might not be useful here.
      <p>
      <h3>Comments that are completely out of left field</h3> Sometimes discussions veer off a bit, but are still related to the original subject.
      That is fine. Hijacking the conversation to promote off-topic commentary is not.
      <p>
      <h3>Threats</h3>No matter how vague — against the author or other commenters. Things can get heated.<p>
      Before you casually mention your foe’s home address, think of your Mother Earth. (Bonus points if you never use the phrase “Mother Earth.”)
      <p>
      <h3>Racism, sexism, homophobia, you get the drift</h3> Completely unacceptable anyone will be blocked/banned and reported.
      <p>
      <h3>Trolling</h3> If you’re a climate denier just out for a good trolling and are not contributing meaningfully to the conversation, we’ll be pushing you back under the bridge.


  </div>
  </body>
</html>

blogbase/dsblog/templates/blog/crypto.html
<!--post.text|safe enables html output and displays Images-->

{% extends 'base.html' %}

{% block content %}
<div class="card">
  <div class="w3-container w3-grey">
    <h3>Coin Market Cap</h3>
  </div>
  <p>
    <script type="text/javascript">
    baseUrl = "https://widgets.cryptocompare.com/";
    var scripts = document.getElementsByTagName("script");
    var embedder = scripts[ scripts.length - 1 ];
    var cccTheme = {"General":{"borderColor":"#000"}};
    (function (){
    var appName = encodeURIComponent(window.location.hostname);
    if(appName==""){appName="local";}
    var s = document.createElement("script");
    s.type = "text/javascript";
    s.async = true;
    var theUrl = baseUrl+'serve/v1/coin/multi?fsyms=BTC,ETH,XMR,LTC,DASH,GNT,ZEC&tsyms=GBP,EUR,USD,BTC';
    s.src = theUrl + ( theUrl.indexOf("?") >= 0 ? "&" : "?") + "app=" + appName;
    embedder.parentNode.appendChild(s);
    })();
    </script>
    <p>
      <script type="text/javascript">
      baseUrl = "https://widgets.cryptocompare.com/";
      var scripts = document.getElementsByTagName("script");
      var embedder = scripts[ scripts.length - 1 ];
      var cccTheme = {"General":{"borderWidth":"1px","borderColor":"#000","headerText":"Coin Conversion"},"Form":{"labelFrom":"From","labelTo":"To"}};
      (function (){
        var appName = encodeURIComponent(window.location.hostname);
        if(appName==""){appName="local";}
        var s = document.createElement("script");
        s.type = "text/javascript";
        s.async = true;
        var theUrl = baseUrl+'serve/v1/coin/converter?fsym=BTC&tsyms=GBP,BTC,USD,EUR';
        s.src = theUrl + ( theUrl.indexOf("?") >= 0 ? "&" : "?") + "app=" + appName;
        embedder.parentNode.appendChild(s);
      })();
      </script>
      <p>
</div>
{% endblock content %}

blogbase/dsblog/templates/blog/images.html
<!--post.text|safe enables html output and displays Images-->

{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
<div class="card">
  <div class="w3-container w3-grey">
    <h1>Astro Images</h1>
  </div>

<div class="w3-row-padding w3-margin-top">
  <div class="w3-third">
    <div class="w3-card">
      <img src="{% static 'images/garden_nightscape.jpg' %}" style="width:100%;cursor:pointer"
    onclick="onClick(this)">
      <div class="w3-container">
        <h5>Garden nightscape</h5>
        One of the very first images I took back In 2016, the foreground Is still too dark but I've removed a lot of the light pollution.
        The ISO is very low because of the urban location where the light pollution was quite heavy.

        <p>Canon EOS 760D</p>
        <p>Sigma 18-35mm Art Lens</p>
        <p>18mm focal length
        <p>F Stop 1.8</p>
        ISO 100
      </div>
    </div>
  </div>

  <div class="w3-third">
    <div class="w3-card">
      <img src="{% static 'images/berneray_beach.jpg' %}" style="width:100%;cursor:pointer"
    onclick="onClick(this)">
      <div class="w3-container">
        <h5>Berneray beach</h5>
        My first trip to Harris in the Outer hebrides produced some incredible scenery, unfortunately there were no clear
        skies that weekend but i did manage to take some amazing day shots. This was one particular favorite, of Bernerary
        beach in the evening.

        <p>Canon EOS 760D</p>
        <p>Sigma 18-35mm Art Lens</p>
        <p>18mm focal length
        <p>F Stop 1.8</p>
        ISO 125
      </div>
    </div>
  </div>

  <div class="w3-third">
    <div class="w3-card">
      <img src="{% static 'images/strond_house.jpg' %}" style="width:100%;cursor:pointer"
    onclick="onClick(this)">
      <div class="w3-container">
        <h5>Harris house</h5>
        Another image i captured was of one of the houses on the main island of Harris. Rugged, remote and absolutely
        stunning. The house felt like it was sat at the edge of the world, as the sheep grazed nearby.

        <p>Canon EOS 760D</p>
        <p>Sigma 18-35mm Art Lens</p>
        <p>18mm focal length
        <p>F Stop 1.8</p>
        ISO 100
      </div>
    </div>
  </div>

</div>
</div>

<div id="modal01" class="w3-modal" onclick="this.style.display='none'">
  <span class="w3-button w3-hover-red w3-xlarge w3-display-topright">&times;</span>
  <div class="w3-modal-content w3-animate-zoom">
    <img id="img01" style="width:100%">
  </div>
</div>
{% endblock content %}

blogbase/dsblog/templates/blog/post_detail.html
{% extends 'base.html' %}

        <!--as there's no for loop in the post_view function in views-->
        <!--the post. tag just pulls directly from the post variable-->
        <!--and the category slug needs to connect to the post model then-->
        <!--it looks for category variable and finally slug in category -->
{% block content %}
    <div class="card">
        Category: <a id="cat-comm-links" class="w3-ul" href="{% url 'dsblog:category_detail' slug=post.category.slug %}">{{ post.category }}</a>
        <p><a class="w3-ul" href="/">HOME</a></p>

        <h1>{{ post.title }}</h1>
        <p>
        {{ post.published_date }} by {{ post.author.get_full_name }}
        <p>
        {{ post.text|safe }}
        <p>

    </div>

    <div class="card">
      <div class="w3-container w3-grey">
      <h2>Comments</h2>
      </div>

    <div id="disqus_thread"></div>
        <script>

          /**
          *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
          *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
          // this.page.url = 'www.darkskiesblog.co.uk/post/{{ post.slug }}/';  // Replace PAGE_URL with your page's canonical URL variable

          var disqus_config = function () {
          this.page.identifier = '/{{ post.slug }}/'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
          };

          (function() { // DON'T EDIT BELOW THIS LINE
          var d = document, s = d.createElement('script');
          s.src = 'https://thedsblog.disqus.com/embed.js';
          s.setAttribute('data-timestamp', +new Date());
          (d.head || d.body).appendChild(s);
          })();
        </script>
        <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  </div>
{% endblock %}

blogbase/dsblog/templates/blog/post_list.html
<!--obj.text|safe enables html output and displays Images-->

{% extends 'base.html' %}

{% block content %}

  {% for obj in items %}
        <!--make sure the links to the category detail and post detail match-->
        <!--the app directory templates then the correct template, and slug matches the for loop-->
        <!--also ensure the django template tags relate to the for temp loop in this case obj-->
    <div class="card">
      <div class="postimage">
        <img src= "{{ obj.image.url }}" width=240 height=190 alt="img">
      </div>

        Category: <a id="cat-comm-links" class="w3-ul" href="{% url 'dsblog:category_detail' slug=obj.category.slug %}">{{obj.category}}</a>

      <div class="posttext">
        <h1><a class="w3-ul" href="{% url 'dsblog:post_detail' slug=obj.slug %}">{{obj.title}}</a></h1>
        <p>{{ obj.tagline|safe }}</p>
        {{ obj.published_date }}
        by {{ obj.author.get_full_name }}</p>
                <!--#disqus_thread addon is to provide unique url link to disqus for comments-->
        <a id="cat-comm-links" class="w3-ul" href="{% url 'dsblog:post_detail' slug=obj.slug %}#disqus_thread">Comments</a>
      </div>
    </div>
  {% endfor %}

  <div class="card">
          {% include 'pagination.html' %}
  </div>
{% endblock content %}